authkeys:
  - /root/.ssh/authorized_keys
  - /home/pavel/.ssh/authorized_keys
bucket: "LoginMonitor"
output: "sum"
log: "test/secure.log"
database: "test/database.db"
color: false
theme:
  username: green
  eventtype: yellow
  eventtime: red
  sourceip: blue
  starttime: green
  endtime: red
  port: blue
